# Generated by Django 5.1.1 on 2025-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0031_workerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Work Started', 'Work Started')], default='Pending', max_length=20),
        ),
    ]
