# Generated by Django 5.0.6 on 2025-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0032_booking_actual_hours_worked_booking_work_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_hours_worked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='work_start_time',
        ),
        migrations.AddField(
            model_name='workerrating',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workerrating',
            name='worker_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
